# Generated by Django 2.0.3 on 2019-08-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(default='Name', max_length=64),
        ),
        migrations.AlterField(
            model_name='onepricefood',
            name='price',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='twopricefood',
            name='largePrice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='twopricefood',
            name='smallPrice',
            field=models.DecimalField(decimal_places=2, default='0.00', max_digits=4, null=True),
        ),
    ]
