# Generated by Django 2.0.3 on 2019-09-08 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_order2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order2',
            new_name='Order',
        ),
        migrations.AddField(
            model_name='food',
            name='category',
            field=models.CharField(default='Category', max_length=64),
        ),
    ]
