# Generated by Django 2.0.3 on 2019-09-09 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_ordercounter_userorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userorder',
            name='toppingAllowance',
        ),
    ]
