# Generated by Django 2.0.3 on 2019-09-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20190909_2334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='user',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='orderitem',
            old_name='amount',
            new_name='orderNumber',
        ),
    ]
