# Generated by Django 2.0.3 on 2019-09-13 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20190911_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='orderNumber',
        ),
    ]
