# Generated by Django 2.0.3 on 2019-09-25 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orderitem_ordernumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='toppingAllowance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='In the shopping cart', max_length=64),
        ),
    ]
