# Generated by Django 2.0.3 on 2019-09-29 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20190925_1218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToppingOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64, null=True)),
                ('name', models.CharField(max_length=64)),
                ('orderItem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.OrderItem')),
            ],
        ),
    ]
