# Generated by Django 2.0.3 on 2019-10-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodorderitem',
            name='isPizza',
            field=models.BooleanField(default=False),
        ),
    ]
